import 'package:flutter/material.dart';

import 'general.dart';

const List imagesArray = [
  'assets/images/level1q1.png',
  'assets/images/level1q2.png',
  'assets/images/level1q3.png',
  'assets/images/level1q4.png',
  'assets/images/level1q5.png',
  'assets/images/level1q6.png',
  'assets/images/level1q7.png',
  'assets/images/level1q8.png',
  'assets/images/level1q9.png',
  'assets/images/level1q10.png',
  'assets/images/l1.png',
  'assets/images/l2.png',
  'assets/images/level1q9.png',
  'assets/images/level1q3.png',
  'assets/images/l3.png',
  'assets/images/l4.png',
  'assets/images/l5.png',
  'assets/images/level1q2.png',
  'assets/images/level1q3.png',
  'assets/images/l6.png',
  'assets/images/t1.png',
  'assets/images/t2.png',
  'assets/images/t3.png',
  'assets/images/level1q3.png',
  'assets/images/t4.png',
  'assets/images/t5.png',
  'assets/images/t6.png',
  'assets/images/t7.png',
  'assets/images/t8.png',
  'assets/images/t9.png',
  'assets/images/g1.png',
  'assets/images/g2.png',
  'assets/images/g3.png',
  'assets/images/g4.png',
  'assets/images/g5.png',
  'assets/images/g6.png',
  'assets/images/g7.png',
  'assets/images/g8.png',
  'assets/images/g9.png',
  'assets/images/g10.png',
];

final List colorsArrays = [
  [kRedFont, kL12],
  [kL22, kBlueBg],
  [kL3, kL32],
  [
    Colors.indigoAccent,
    Colors.deepPurple,
  ]
];
final List choice1Array = [
  'Berlin',
  'Venus',
  'H2O',
  'Vincent van Gogh',
  'Thermometer',
  'Elephant',
  'Go',
  'Isaac Newton',
  'Carbon monoxide',
  'Egypt',
  'William Shakespeare',
  'Heart',
  'Oxygen',
  'Ir',
  'Yen',
  'Charles Dickens',
  'Atlantic Ocean',
  'Jupiter',
  'H',
  'Rome',
  'Pablo Picasso',
  'Watt',
  'To Kill a Mockingbird',
  'Si',
  'China',
  'J.R.R. Tolkien',
  'Sydney',
  'Deoxyribonucleic acid',
  'Hydrogen and Oxygen',
  'Great White Shark',
  'Rafah',
  'Al-Mughraqa',
  'Erez Crossing',
  'Tell es-Sakan',
  'Shuja\'iyya',
  'Al-Bureij Refugee Camp',
  'Great Omari Mosque',
  'Deir al-Balah',
  'UNRWA Food Distribution Center',
  'Al-Bardawil Lake',
];
final List choice2Array = [
  'Paris',
  'Mars',
  'CO2',
  'Leonardo da Vinci',
  'Barometer',
  'Blue whale',
  'Au',
  'Albert Einstein',
  'Nitrogen',
  'Mexico',
  'Mark Twain',
  'Liver',
  'Hydrogen',
  'Fe',
  'Dollar',
  'Jane Austen',
  'Indian Ocean',
  'Mars',
  'He',
  'Paris',
  'Vincent van Gogh',
  'Ampere',
  'Lord of the Flies',
  'Ag',
  'Japan',
  'George R.R. Martin',
  'Melbourne',
  'Dynamic nucleic acid',
  'Nitrogen and Oxygen',
  'Hammerhead Shark',
  'Khan Yunis',
  'Al-Shati Refugee Camp',
  'Karni Crossing',
  'Tell el-Fara',
  'Rimal',
  'Al-Maghazi Refugee Camp',
  'Ansar Mosque',
  'Khan Younis',
  'Erez Industrial Zone',
  'Ibn Rushd Park',
];
final List choice3Array = [
  'Rome',
  'Mercury',
  'O2',
  'Pablo Picasso',
  'Hygrometer',
  'Lion',
  'Gl',
  'Galileo Galilei',
  'Carbon dioxide',
  'Greece',
  'Jane Austen',
  'Skin',
  'Methane',
  'Io',
  'Euro',
  'Emily Bronte',
  'Pacific Ocean',
  'Saturn',
  'Ho',
  'London',
  'Claude Monet',
  'Volt',
  '1984',
  'Sl',
  'South Korea',
  'C.S. Lewis',
  'Canberra',
  'Double nitrogen atom',
  'Carbon and Hydrogen',
  'Gaza City',
  'Al-Waha Resort',
  'Rafah Crossing',
  'Anthedon Harbor',
  'Nuseirat',
  'Jabalia Refugee Camp',
  'Sheikh Radwan Mosque',
  'Anthedon Harbor',
  'Port of Gaza',
  'Martyrs Park',
];
final List questionsArrays = [
  'What is the capital of France?',
  'Which planet is closest to the Sun?',
  'What is the chemical symbol for water?',
  'Who painted the Mona Lisa?',
  'Which instrument is used to measure atmospheric pressure?',
  'What is the largest mammal on Earth?',
  'What is the symbol for the element gold?',
  'Which famous scientist developed the theory of relativity?',
  'What gas do plants absorb from the atmosphere during photosynthesis?',
  'In which country would you find the Great Pyramid of Giza?',
  'Who wrote the play "Romeo and Juliet"?',
  'What is the largest organ in the human body?',
  'Which gas do plants release during photosynthesis?',
  'What is the chemical symbol for iron?',
  'What is the currency of Japan?',
  'Who wrote the famous novel "Pride and Prejudice"?',
  'What is the largest ocean on Earth?',
  'Which planet is known as the "Red Planet"?',
  'What is the chemical symbol for helium?',
  'In which city would you find the Eiffel Tower?',
  'Who painted the famous artwork "The Starry Night"?',
  'What is the unit of measurement for electric current?',
  'Which novel features the characters Scout, Atticus Finch, and Boo Radley?',
  'What is the chemical symbol for silver?',
  'Which country is known as the "Land of the Rising Sun"?',
  'Who is the author of the epic fantasy series "A Song of Ice and Fire"?',
  'What is the capital of Australia?',
  'In physics, what does the acronym "DNA" stand for?',
  'Which two elements combine to form water?',
  'What is the largest species of shark?',
  'Gaza\'s largest city?',
  'Gaza\'s famous coastal area?',
  'Gaza-Egypt border crossing?',
  'Ancient Roman ruins in Gaza?',
  'Vibrant markets in Gaza City?',
  'Northern Gaza Strip refugee camp?',
  'Famous mosque in Gaza?',
  'Ancient port city in southern Gaza?',
  'UN-run facility for Palestinian refugees?',
  'Recreational park in Gaza?',
];
List<int> answersArray = [
  2,
  3,
  1,
  2,
  2,
  2,
  2,
  2,
  3,
  1,
  1,
  3,
  1,
  2,
  1,
  2,
  3,
  2,
  2,
  2,
  2,
  2,
  1,
  2,
  2,
  2,
  3,
  1,
  1,
  3,
  1,
  3,
  3,
  2,
  2,
  3,
  1,
  3,
  1,
  2
];
